python graphLine.py HCstart1_6 1
python graphLine.py HCstart1_6 2
python graphLine.py HCstart1_6 3
python graphLine.py HCstart2_6 1
python graphLine.py HCstart2_6 2
python graphLine.py HCstart2_6 3
python graphLine.py EAstart1_6 1
python graphLine.py EAstart1_6 2
python graphLine.py EAstart1_6 3
python graphLine.py EAstart2_6 1
python graphLine.py EAstart2_6 2
python graphLine.py EAstart2_6 3
python graphLine.py HCstart1_8 1
python graphLine.py HCstart1_8 2
python graphLine.py HCstart1_8 3
python graphLine.py HCstart2_8 1
python graphLine.py HCstart2_8 2
python graphLine.py HCstart2_8 3
python graphLine.py EAstart1_8 1
python graphLine.py EAstart1_8 2
python graphLine.py EAstart1_8 3
python graphLine.py EAstart2_8 1
python graphLine.py EAstart2_8 2
python graphLine.py EAstart2_8 3
